---
title: "Complexity"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(readxl)
library(writexl)
library(googledrive)
library(childesr)
library(ggthemes)
library(ggpubr)
library(grid)

```

# Read in word selection and complexity ratings

```{r}
# drive_download("https://docs.google.com/spreadsheets/d/1xH3EOFpU9AQ7z9MtwQpnkjhbJOm8KyqV9SvZzdpezhw/edit#gid=0",
#                path = "./data/clt_new_words.xlsx",
#                overwrite = T)

comp <- read_xlsx("../data/clt_new_words.xlsx")%>%
  filter(select == "x")%>%
  select(-select)%>%
  rename(sem_complexity = `Complexity score`,
         aoa = aoa_german_comb)%>%
  mutate(aoa = as.numeric(str_replace(aoa, ",", ".")))

```

# Frequency from childes

```{r}
# tokens <- comp$german
# 
# cd <- get_types(collection = "German", 
#           type = tokens)
# 
# write_csv(cd,"../data/clt_childes_freq.csv")

cd <- read_csv("../data/clt_childes_freq.csv")

cdf <- cd %>%
  mutate(german = tolower(gloss))%>%
  group_by(german)%>%
  summarise(childes_freq = sum(count))


```

# Complexity scores

## Correlation between scores

```{r}
c1 <- comp%>%
  select(german, aoa,word_freq, sem_complexity)%>%
  left_join(cdf)%>%
  mutate_if(is.numeric, scale, center = T, scale = T)%>%
  pivot_longer(names_to = "measure", values_to = "score", cols = c(aoa,word_freq, sem_complexity, childes_freq))


c2 <- c1%>%
  left_join(c1 %>% rename(score2 = score, measure2 = measure),by = c("german"))%>%
  filter(measure != measure2)%>%
  rowwise()%>%
  mutate(ex = paste(sort(c(measure2, measure)), collapse = " - "))%>%
  group_by(german)%>%
  distinct(ex, .keep_all = T)%>%
  mutate(measure = factor(measure, levels = c("aoa", "childes_freq", "word_freq","sem_complexity")))
  

p <- ggplot(c2, aes(x = score, y = score2))+
  geom_point( alpha = .25)+
  geom_abline(intercept = 0 , slope = 1, lty = 2, alpha = .4)+
  facet_grid(measure~measure2, switch ="y")+
  theme_few()+
  geom_smooth(method = lm)+
  xlim(-2,2)+
  scale_y_continuous(position = "right", limits = c(-2,2))+
  labs(x = "", y = "")+
  stat_cor(method = "pearson", size = 3, r.accuracy = 0.01, cor.coef.name = "r")

g = ggplotGrob(p)
remove <- c("panel-3-2", "panel-3-3", "panel-2-3")
pos <- g$layout$name %in% remove
g$grobs <- g$grobs[!pos]
g$layout <- g$layout[!pos, ]
idx <- which(g$layout$name %in% c("axis-b-2", "axis-b-3"));
g$layout[idx, c("t", "b")] <- g$layout[idx, c("t", "b")] - c(2, 4);

idy <- which(g$layout$name %in% c("axis-r-2", "axis-r-3"));
g$layout[idy, c("l", "r")] <- g$layout[idy, c("l", "r")] - c(2, 4);


pp <- grid.arrange(arrangeGrob(g))

ggsave("../graphs/complexity_correlation.png", pp)
```


## Calculate complexity score

```{r}
comp%>%
  select(german, aoa,word_freq, sem_complexity)%>%
  mutate_if(is.numeric, scale, center = T, scale = T)%>%
  mutate(complex = aoa + word_freq + sem_complexity)%>%
  mutate(german = fct_reorder(german, desc(complex)))%>%
  ggplot(aes(y = complex, x = german))+
  geom_hline(yintercept = 0, lty = 2, alpha = .5)+
  geom_point(size = 2, col = "firebrick")+ 
  theme_minimal()+
  ylim(-3,3)+
  theme(axis.text.x=element_text(angle=45, hjust=1))
```

