---
title: "trial sequence"
output: html_document
---

```{r setup, include=FALSE}
library(readxl)
library(writexl)
library(gsheet)
library(tidyverse)
library(permute)
library(faux)
```

```{r}
aoa <-  read_xlsx("../data/word_list.xlsx")

clt <- gsheet2tbl('https://docs.google.com/spreadsheets/d/1xH3EOFpU9AQ7z9MtwQpnkjhbJOm8KyqV9SvZzdpezhw/edit#gid=469786312')
```

```{r}
trials <- clt%>%
  rename(german = target_de,
         dist3_unrelated = `dist 3 / unrelated_de`,
         dist1_semantic = `dist 1 / semantic_de`,
         dist2_phonological = `dist 2 / phonological_de`)%>%
  select(trial_nr,german, dist1_semantic, dist2_phonological, dist3_unrelated, upper_left, upper_right, lower_left, lower_right)%>%
  left_join(aoa%>%select(german,aoa_german_comb)%>% distinct(german, .keep_all = TRUE))%>%
  arrange(aoa_german_comb)%>%
  mutate(item = row_number(), 
         item2 = rnorm_pre(item, r = .85))%>%
  mutate(cor = cor(item, item2))%>%
  arrange(item2)

trials%>%
  select(upper_left, upper_right, lower_left, lower_right)

write_xlsx(trials, "../data/clt_trial_order.xlsx")
```

```{r}
clt_new <- gsheet2tbl('https://docs.google.com/spreadsheets/d/1xH3EOFpU9AQ7z9MtwQpnkjhbJOm8KyqV9SvZzdpezhw/edit#gid=1189855701')
```

```{r}
new_trials <- clt_new%>%
  mutate(trial_nr_2 = rnorm_pre(trial_nr, r = .95))%>%
  arrange(trial_nr_2)



write_xlsx(new_trials, "../data/clt_trial_order_2.xlsx")
```

